site_name: Broadway Insights
site_url: https://ethaniel2024.github.io/broadway-project/

theme:
  name: mkdocs

nav:
  - Home: index.md
  - Analysis Summary: analysis.md
  - Tutorial: tutorial.md
  - Function Reference: reference.md
  - Streamlit App: https://broadway-project-bksewnjwtb4z5zpydtmuft.streamlit.app/
  - GitHub Repo: https://github.com/ethaniel2024/broadway-project
  - Data Acquisition Repo: https://github.com/jessieaolsen-sys/data-aquistion-code
